import { writeFileSync } from 'fs'
import { resolve } from 'path'
import type { Command } from 'commander'
import {
  getRepoRoot,
  loadConfig,
  getBackend,
  gatherContext,
  generateAgentsMd,
  generateClaudeMd,
  AGENTS_MD_SIGNATURE,
  OverwriteError,
  checkExistingFile,
} from '@emartai/mindr-core'

// ---------------------------------------------------------------------------
// ANSI helpers — no external dep
// ---------------------------------------------------------------------------
const c = {
  green:  (s: string) => `\x1b[32m${s}\x1b[0m`,
  cyan:   (s: string) => `\x1b[36m${s}\x1b[0m`,
  yellow: (s: string) => `\x1b[33m${s}\x1b[0m`,
  bold:   (s: string) => `\x1b[1m${s}\x1b[0m`,
  dim:    (s: string) => `\x1b[2m${s}\x1b[0m`,
}

// ---------------------------------------------------------------------------
// Summary printer
// ---------------------------------------------------------------------------

function printSummary(
  label: string,
  outputPath: string,
  meta: { name: string; version: string; language: string },
  stack: Array<{ name: string }>,
  conventionCount: number,
  decisionCount: number,
  debtCount: number,
): void {
  const stackStr =
    stack.length === 0
      ? c.dim('(none detected)')
      : stack.slice(0, 3).map((s) => s.name).join(', ') +
        (stack.length > 3 ? c.dim(` +${stack.length - 3} more`) : '')

  process.stdout.write(
    [
      '',
      `  ${c.green('✓')} ${c.bold(`Generated ${label}`)}  ${c.dim(outputPath)}`,
      '',
      `  ${c.cyan('Project:')}     ${meta.name}${meta.version !== '0.0.0' ? ` v${meta.version}` : ''} ${c.dim(`(${meta.language})`)}`,
      `  ${c.cyan('Stack:')}       ${stackStr}`,
      `  ${c.cyan('Conventions:')} ${conventionCount} rules across languages`,
      `  ${c.cyan('Decisions:')}   ${decisionCount} recent`,
      `  ${c.cyan('Debt items:')}  ${debtCount} active`,
      '',
    ].join('\n'),
  )
}

// ---------------------------------------------------------------------------
// Core generate logic
// ---------------------------------------------------------------------------

async function doGenerate(
  target: 'agents-md' | 'claude-md',
  outputPath: string,
  force: boolean,
): Promise<void> {
  const absPath = resolve(outputPath)

  checkExistingFile(absPath, force, AGENTS_MD_SIGNATURE)

  const repoRoot = await getRepoRoot(process.cwd())
  const config = loadConfig(repoRoot)
  const backend = getBackend(config)
  const ctx = await gatherContext(repoRoot, backend)

  const md =
    target === 'agents-md'
      ? await generateAgentsMd(repoRoot, backend, { context: ctx })
      : await generateClaudeMd(repoRoot, backend, { context: ctx })

  writeFileSync(absPath, md, 'utf8')

  const totalConventions = ctx.conventions.reduce((s, p) => s + p.conventions.length, 0)
  printSummary(
    target === 'agents-md' ? 'AGENTS.md' : 'CLAUDE.md',
    absPath,
    ctx.meta,
    ctx.stack,
    totalConventions,
    ctx.decisions.length,
    ctx.debt.length,
  )
}

function handleErr(err: unknown): never {
  if (err instanceof OverwriteError) {
    process.stderr.write(`\n  ${c.yellow('!')} ${err.message}\n\n`)
    process.exit(1)
  }
  throw err
}

// ---------------------------------------------------------------------------
// Commander wiring
// ---------------------------------------------------------------------------

export function addGenerateCommands(program: Command): void {
  const gen = program
    .command('generate')
    .description('Generate AI agent instruction files from observed patterns')
    .option('--all', 'Generate both AGENTS.md and CLAUDE.md')
    .option('--force', 'Overwrite even if file was not generated by Mindr')

  gen.action(async (opts: { all?: boolean; force?: boolean }) => {
    if (!opts.all) { gen.help(); return }
    try {
      await doGenerate('agents-md', './AGENTS.md', opts.force ?? false)
      await doGenerate('claude-md',  './CLAUDE.md', opts.force ?? false)
    } catch (err) { handleErr(err) }
  })

  gen
    .command('agents-md')
    .description('Generate AGENTS.md — structured instructions for AI coding agents')
    .option('-o, --output <path>', 'Output path', './AGENTS.md')
    .option('--force', 'Overwrite even if file was not generated by Mindr')
    .action(async (opts: { output: string; force?: boolean }) => {
      try { await doGenerate('agents-md', opts.output, opts.force ?? false) }
      catch (err) { handleErr(err) }
    })

  gen
    .command('claude-md')
    .description('Generate CLAUDE.md — instructions for Claude Code')
    .option('-o, --output <path>', 'Output path', './CLAUDE.md')
    .option('--force', 'Overwrite even if file was not generated by Mindr')
    .action(async (opts: { output: string; force?: boolean }) => {
      try { await doGenerate('claude-md', opts.output, opts.force ?? false) }
      catch (err) { handleErr(err) }
    })
}
