// AGENTS.md generator — structured instruction file for AI coding agents.

import { readFileSync, existsSync } from 'fs'
import type { MemoryBackend } from '../storage/backend.js'
import type { GenerateContext } from './context.js'
import type { Convention, ConventionProfile } from '../conventions/detector.js'
import { gatherContext } from './context.js'

export const SIGNATURE = '<!-- mindr-generated -->'

export interface GenerateOptions {
  /** Pre-built context — bypasses all I/O (used in tests). */
  context?: GenerateContext
}

// ---------------------------------------------------------------------------
// Overwrite guard — used by the CLI command
// ---------------------------------------------------------------------------

export class OverwriteError extends Error {
  constructor(path: string) {
    super(
      `${path} already exists and was not generated by Mindr.\n` +
        `  Use --force to overwrite it anyway.`,
    )
    this.name = 'OverwriteError'
  }
}

export function checkExistingFile(absPath: string, force: boolean, signature: string): void {
  if (!existsSync(absPath)) return
  const content = readFileSync(absPath, 'utf8')
  if (content.includes(signature)) return
  if (force) return
  throw new OverwriteError(absPath)
}

// ---------------------------------------------------------------------------
// Shared rendering helpers
// ---------------------------------------------------------------------------

const CATEGORY_LABELS: Record<string, string> = {
  functionNames:   'Function names',
  variableNames:   'Variable names',
  classNames:      'Class / type names',
  fileNames:       'File names',
  testFilePattern: 'Test file pattern',
}

function renderConventionTable(profile: ConventionProfile): string {
  const top = profile.conventions
    .slice()
    .sort((a, b) => b.score - a.score)
    .slice(0, 5)

  if (top.length === 0) return '_No convention data yet._\n'

  const rows = top.map((c: Convention) => {
    const label = CATEGORY_LABELS[c.category] ?? c.category
    return `| ${label} | \`${c.pattern}\` | ${c.score}% | ${c.sampleCount} |`
  })

  return [
    '| Category | Style | Confidence | Samples |',
    '|----------|-------|-----------|---------|',
    ...rows,
  ].join('\n') + '\n'
}

function renderDecisions(decisions: GenerateContext['decisions']): string {
  if (decisions.length === 0) return '_No decisions recorded yet._\n'

  return decisions
    .map((d) => {
      const date = d.metadata?.['date']
        ? String(d.metadata['date']).slice(0, 10)
        : d.createdAt.slice(0, 10)
      const trigger = d.metadata?.['trigger'] ? ` *(${d.metadata['trigger']})*` : ''
      const body = d.content.replace(/^Decision:\s*/i, '')
      return `- **${date}** — ${body}${trigger}`
    })
    .join('\n') + '\n'
}

function renderDebt(debt: GenerateContext['debt']): string {
  if (debt.length === 0) return '_No active debt items._\n'

  return debt
    .map((d) => {
      const file = d.metadata?.['file'] ? `\`${d.metadata['file']}:${d.metadata['line']}\` — ` : ''
      const keyword = d.metadata?.['keyword'] ? `**${d.metadata['keyword']}**` : ''
      const body = keyword
        ? d.content.replace(
            /^(TODO|FIXME|HACK|XXX) at [^—]+— /i,
            '',
          )
        : d.content
      return `- ${file}${keyword ? `${keyword}: ` : ''}${body}`
    })
    .join('\n') + '\n'
}

function renderCommands(commands: GenerateContext['commands']): string {
  if (commands.length === 0) {
    return '_No commands detected. Add scripts to `package.json`/`Makefile` and re-run `mindr generate`._\n'
  }
  const rows = commands.map((c) => `| ${c.label} | \`${c.command}\` |`)
  return [
    '| Task | Command |',
    '|------|---------|',
    ...rows,
  ].join('\n') + '\n'
}

function renderStack(stack: GenerateContext['stack']): string {
  if (stack.length === 0) return '_Could not detect stack from project files._\n'

  let current: string | null = null
  const lines: string[] = []
  for (const item of stack) {
    if (item.category !== current) {
      current = item.category
      if (lines.length > 0) lines.push('')
      lines.push(`**${current.charAt(0).toUpperCase() + current.slice(1)}**`)
    }
    lines.push(`- ${item.name} — ${item.role}`)
  }
  return lines.join('\n') + '\n'
}

// ---------------------------------------------------------------------------
// AGENTS.md renderer
// ---------------------------------------------------------------------------

export async function generateAgentsMd(
  repoRoot: string,
  backend: MemoryBackend,
  opts: GenerateOptions = {},
): Promise<string> {
  const ctx = opts.context ?? await gatherContext(repoRoot, backend)
  const { meta, commands, stack, conventions, decisions, debt } = ctx

  const lines: string[] = []

  lines.push(SIGNATURE)
  lines.push('')
  lines.push(`# ${meta.name}`)
  lines.push('')
  if (meta.description) {
    lines.push(meta.description)
    lines.push('')
  }
  const badges: string[] = []
  if (meta.repoUrl) badges.push(`**Repository:** ${meta.repoUrl}`)
  if (meta.version && meta.version !== '0.0.0') badges.push(`**Version:** ${meta.version}`)
  if (meta.language !== 'unknown') badges.push(`**Language:** ${meta.language}`)
  if (badges.length > 0) {
    lines.push(badges.join('  \n'))
    lines.push('')
  }

  // --- Commands (agents need these first) ---
  lines.push('## Commands')
  lines.push('')
  lines.push(renderCommands(commands).trimEnd())
  lines.push('')

  // --- Stack & Architecture ---
  lines.push('## Stack & Architecture')
  lines.push('')
  lines.push(renderStack(stack).trimEnd())
  lines.push('')

  // --- Conventions ---
  lines.push('## Conventions')
  lines.push('')
  if (conventions.length === 0) {
    lines.push('_No convention analysis yet. Commit some code to let Mindr learn your patterns._')
  } else {
    for (const profile of conventions) {
      lines.push(`### ${profile.language.charAt(0).toUpperCase() + profile.language.slice(1)}`)
      lines.push('')
      lines.push(renderConventionTable(profile).trimEnd())
    }
  }
  lines.push('')

  // --- Recent Decisions ---
  lines.push('## Recent Decisions')
  lines.push('')
  lines.push(renderDecisions(decisions).trimEnd())
  lines.push('')

  // --- Active Warnings ---
  lines.push('## Active Warnings')
  lines.push('')
  lines.push('### Technical Debt')
  lines.push('')
  lines.push(renderDebt(debt).trimEnd())
  lines.push('')

  return lines.join('\n')
}
